#!/bin/bash

sudo apt-get update
sudo apt-get install -y build-essential
sudo apt-get install -y libssl-dev

sudo apt-get install -y python-software-properties
sudo add-apt-repository ppa:chris-lea/node.js
sudo apt-get update
sudo apt-get install -y nodejs

sudo apt-get install -y lynx
